<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="pc" failures="1" tests="3" name="Default test" time="32.711" errors="0" timestamp="17 Nov 2018 02:49:46 GMT">
  <testcase classname="com.demoaut.newtours.TestCases.BookTicketTest" name="ticketBookingTest" time="8.448"/>
  <testcase classname="com.demoaut.newtours.TestCases.InvalidUserTest" name="userValidation" time="1.809">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.demoaut.newtours.TestCases.InvalidUserTest.userValidation(InvalidUserTest.java:28)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- userValidation -->
  <testcase classname="com.demoaut.newtours.TestCases.ValidateUSerTest" name="userValidation" time="5.653"/>
  <testcase classname="com.demoaut.newtours.TestCases.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="com.demoaut.newtours.TestCases.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="com.demoaut.newtours.TestCases.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
</testsuite> <!-- Default test -->
